# Generated by Django 5.1.7 on 2025-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('INITIAL', 'Initial'), ('WORK_IN_PROGRESS', 'Work in progress'), ('PAUSED', 'Paused'), ('REST', 'Break')], default='INITIAL', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StatusRecord',
        ),
    ]
